const cartActionTypes = {
    TOGGLE_CART:'TOGGLE_CART',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    REMOVE_FROM_ITEM_QUANTITY: 'REMOVE_FROM_ITEM_QUANTITY',
    ADD_TO_ITEM_QUANTITY: 'ADD_TO_ITEM_QUANTITY',
    CLEAR_CART: 'CLEAR_CART'
}

export default cartActionTypes;